_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.13.2
            "5": 0.19.6
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.6
            "13": windows-amd64
architecture:
    value: TVAE
dataset:
    value: Physics
epochs:
    value: 200
learning_rate:
    value: 0.07
