_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.13.2
            "5": 0.19.6
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.6
            "13": windows-amd64
batch_size:
    value: 1000
categorical_columns:
    value:
        - HouseAge_Cat
data_dim:
    value: 104
discriminator_lr:
    value: 0.002
epochs:
    value: 100
generator_lr:
    value: 0.005
n_categories:
    value: 5
noise_dim:
    value: 100
pac:
    value: 5
